# Generated by Django 2.2 on 2019-04-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='cross_cities',
            new_name='across_cities',
        ),
    ]
